### ISSUE TITLE
Properly set `site.github.url` when in Jekyll.development

### ISSUE THREAD

**Issue by benbalter** [jekyll/github-metadata#47]
When run locally, `site.github.url` should be `localhost:4000` (or the proper URL), to allow `site.github.url` to always be trusted to render the proper path to assets and other links, both locally and in production.

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least
three months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If you can still reproduce this error on the <pre>3.1-stable</pre> or <pre>master</pre> branch,
please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider building it first as a plugin. Jekyll 3 introduced
[hooks](http://jekyllrb.com/docs/plugins/#hooks) which provide convenient access points throughout
the Jekyll build pipeline whereby most needs can be fulfilled. If this is something that cannot be
built as a plugin, then please provide more information about why in order to keep this issue open.

Thank you for all your contributions.

**Comment by gauntface** [comment]
This is still occuring.

**Comment by boturnbow** [comment]
I still have this same problem as well with all my existing sites. To test, I created a [new jekyll site](https://github.com/boturnbow/meta-test), added the metadata gem and added some variable output to index.html. When run locally I do not get the results that I expect for the variables that I output:

    jekyll.environment: development
    site.github.pages_env: development
    site.url: 
    site.baseurl: 
    site.github.url: http://github.com/pages/boturnbow/meta-test

**I expected site.github.url: http://localhost:4000**. The results are the same whether I pass a JEKYLL_GITHUB_TOKEN or not.

When built on Github pages, the output is:

    jekyll.environment: production
    site.github.pages_env: dotcom
    site.url: https://boturnbow.github.io
    site.baseurl: /meta-test
    site.github.url: https://boturnbow.github.io/meta-test

Which works great there.

**Comment by retorquere** [comment]
I think I have a similar issue but with this config:

```
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

repository: retorquere/zotero-better-bibtex

permalink: pretty

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
```

`site.github.url` is `https://github.com/pages/retorquere/zotero-better-bibtex` in development.
